export const INSERT_NEW_ADDRESS = 'INSERT_NEW_ADDRESS';
export const POINT_NEW_LOCATION = 'INSERT_NEW_LOCATION';
export const SAVE_AUTOCOMPLETE_RESULT = 'SAVE_AUTOCOMPLETE_RESULT';
export const GOOGLE_MAP_SUCCESS = 'GOOGLE_MAP_SUCCESS';
export const GOOGLE_MAP_FAILED = 'GOOGLE_MAP_FAILED';
export const SET_MAP_LOCATION = 'SET_MAP_LOCATION';
export const SET_PASS_SEARCH = 'SET_PASS_SEARCH';
